name: boardtrack
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  get_it: ^7.6.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true